workflows:
  android-apk:
    name: Dream Arena Android APK

    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install npm packages
        script: |
          npm install

      - name: Expo prebuild Android
        script: |
          npx expo prebuild --platform android --clean

     
- name: Build Android App Bundle
  script: |
    cd android
    ./gradlew bundleRelease

artifacts:
  - android/app/build/outputs/bundle/release/*.aab